# Generated by Django 3.2.9 on 2022-02-12 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluckbuster', '0002_alter_banner_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='technology',
        ),
        migrations.AddField(
            model_name='banner',
            name='ranking',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
