# Generated by Django 3.2.9 on 2022-02-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluckbuster', '0003_auto_20220212_1106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='ranking',
            field=models.FloatField(max_length=20, null=True),
        ),
    ]
