# Generated by Django 4.0.2 on 2022-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluckbuster', '0005_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200, unique=True), max_length=255),
        ),
    ]
