# Generated by Django 3.2.9 on 2022-02-12 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bluckbuster', '0005_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='video',
            field=models.FileField(default=django.utils.timezone.now, upload_to='bluckbuster/media/video'),
            preserve_default=False,
        ),
    ]
