# Generated by Django 4.0.2 on 2022-02-17 12:04

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bluckbuster', '0006_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='product_name', unique=True),
        ),
    ]
