# Generated by Django 4.0.2 on 2022-02-17 12:09

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluckbuster', '0008_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=models.CharField(max_length=200, unique=True), max_length=100, null=True, unique=True),
        ),
    ]
