# Generated by Django 4.0.2 on 2022-02-17 12:11

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bluckbuster', '0009_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
