from django.urls import path

from . import views

urlpatterns = [

    path('', views.index, name='bluckbuster'),
    path('indexlight', views.index_light, name='indexlight'),
    path('landing', views.landing, name='landing'),
    path('moviegridlight', views.moviegrid_light, name='moviegridlight'),
    path('moviegrid', views.moviegrid, name='moviegrid'),
    path('moviegridfwlight', views.moviegridfw_light, name='moviegridfwlight'),
    path('moviegridfw', views.moviegridfw, name='moviegridfw'),
    path('movielistlight', views.movielist_light, name='movielistlight'),
    path('movielist', views.movielist, name='movielist'),
    path('base', views.base, name='base'),
    path('_404page', views._404page, name='_404page'),
    path('blogdetail', views.blogdetail, name='blogdetail'),
    path('blogdetail_light', views.blogdetail_light, name='blogdetail_light'),
    path('bloggrid_light', views.bloggrid_light, name='bloggrid_light'),
    path('bloglist', views.bloglist, name='bloglist'),
    path('bloglist_light', views.bloglist_light, name='bloglist_light'),
    path('celebritygrid01', views.celebritygrid01, name='celebritygrid01'),
    path('celebritygrid01_light', views.celebritygrid01_light, name='celebritygrid01_light'),
    path('movielist', views.movielist, name='movielist'),
    path('celebritygrid02', views.celebritygrid02, name='celebritygrid02'),
    path('celebritygrid02_light', views.celebritygrid02_light, name='celebritygrid02_light'),
    path('celebritylist', views.celebritylist, name='celebritylist'),
    path('celebritylist_light', views.celebritylist_light, name='celebritylist_light'),
    path('celebritysingle', views.celebritysingle, name='celebritysingle'),
    path('celebritysingle_light', views.celebritysingle_light, name='celebritysingle_light'),
    path('comingsoon', views.comingsoon, name='comingsoon'),
    path('homev2', views.homev2, name='homev2'),
    path('homev2_light', views.homev2_light, name='homev2_light'),
    path('homev3', views.homev3, name='homev3'),
    path('homev3_light', views.homev3_light, name='homev3_light'),
    path('blogdetail_light', views.blogdetail_light, name='blogdetail_light'),
    path('bloggrid', views.bloggrid, name='bloggrid'),
    path('seriessingle_light', views.seriessingle_light, name='seriessingle_light'),
    path('userfavoritegrid', views.userfavoritegrid, name='userfavoritegrid'),
    path('userfavoritegrid_light', views.userfavoritegrid_light, name='userfavoritegrid_light'),
    path('userfavoritelist', views.userfavoritelist, name='userfavoritelist'),
    path('userfavoritelist_light', views.userfavoritelist_light, name='userfavoritelist_light'),
    path('userprofile', views.userprofile, name='userprofile'),
    path('userprofile_light', views.userprofile_light, name='userprofile_light'),
    path('userrate', views.userrate, name='userrate'),
    path('userrate_light', views.userrate_light, name='userrate_light'),
    path('moviesingle', views.moviesingle, name='moviesingle'),
]
